mindmap
  ((IntelliGen))
    RangeSense: Milimeter Wave, human presence detection radar
    ::icon(fa fa-broadcast-tower)
        Physical Security / Entry control and egress detection.
        ::icon(fa fa-door-closed)
        Safety zone: Automated shutdown of hazards
        ::icon(fa fa-hard-hat)
        Shoplifting deterrent: AI analysis of persons close to store shelf.
        ::icon(fa fa-shopping-cart)
    SoundSense: Configurable sound threshold trigger.
    ::icon(fa fa-microphone)
        EarlyLight: Early detection and intervention for mental health maintenance
        ::icon(fa fa-person)
            School canteen: bullying detection
            Mass events: crowd management

        SmartClime: MicroClimate control through AI detection of people in rooms.
        ::icon(fa fa-building)
            Fixed Structures
            Mobile Structures
